import Head from 'next/head'
import Container from "./components/_container"
import Navbar from './components/_navbar'
import Content from './components/_content'

export default function Home() {
  return (
    <div>
      <Head>
        <title>The Times</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container>
          <Navbar />
          <Content>
            <h1 className="text-9xl">News and Stuff</h1>
          </Content>
        </Container>
      </main>
    </div>
  )
}
